name: Lint the test files

on:
  push:
    paths:
      - "tests/**"
  pull_request:
    paths:
      - "tests/**"
  workflow_dispatch: {}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Verify failing tests and orphaned tests
      run: |
        cd tests/test_cases
        python ../../.github/workflows/lint-tests/lint.py